// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4AQ2D-ircxvXZCjn0a7uSwUrOuednejY',
    appId: '1:596625399923:web:c8f919cd667386e50cca06',
    messagingSenderId: '596625399923',
    projectId: 'pos2pos2ukmfirebase',
    authDomain: 'pos2pos2ukmfirebase.firebaseapp.com',
    storageBucket: 'pos2pos2ukmfirebase.appspot.com',
    measurementId: 'G-0EX9R8JNPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXh8eUj_8M0RrIi9ElUkPMBYFu80OU5wk',
    appId: '1:596625399923:android:1257d99ab161077c0cca06',
    messagingSenderId: '596625399923',
    projectId: 'pos2pos2ukmfirebase',
    storageBucket: 'pos2pos2ukmfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtD5QBdvWI3uLzLtloBZpPcqXw7ZP--0E',
    appId: '1:596625399923:ios:039ba80216492ffc0cca06',
    messagingSenderId: '596625399923',
    projectId: 'pos2pos2ukmfirebase',
    storageBucket: 'pos2pos2ukmfirebase.appspot.com',
    iosClientId: '596625399923-e4ftj85oql8uqh6ohol895l4m0989gid.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
